In [3]:
# sklearn 모듈의 tree import
from sklearn import tree
from os import system                 # graphviz 라이브러리 설치를 위함

# graphviz 라이브러리 설치 // 아래 예제에서 오류나는 경우 anaconda prompt에서 설치바람
system("pip install graphviz")


Defaulting to user installation because normal site-packages is not writeable


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# 데이터가공

In [10]:
import pandas as pd

data = pd.read_csv("./human4.csv")

data

name  season season2   vl  va  vb   vh   vs   vv   
0           winter (92).jpg  winter  winter  189   9  13   11   72  211  \
1           winter (94).jpg  winter  winter  179   9   6    5   44  197   
2           winter (84).jpg  winter  winter  176  13  14    8   76  200   
3           winter (92).jpg  winter  winter  171  23  56  114  170  131   
4           winter (80).jpg  winter  winter  162   7   6    7   45  180   
...                     ...     ...     ...  ...  ..  ..  ...  ...  ...   
2991  autumn (7) (copy).jpg  autumn  autumn    2  23  57   18  176   21   
2992        autumn (14).PNG  autumn  autumn    2  18  10   18   70   37   
2993        autumn (14).PNG  autumn  autumn    1  15  32    3  116   23   
2994  autumn (1) (copy).jpg  autumn  autumn    1  10  13   11   13   13   
2995        autumn (14).PNG  autumn  autumn    1   1  30    7  108    4   

          l    a    b   h    s    v  
0     189.0  137  141  11   72  211  
1     179.0  137  134   5   44  197  
2     176.0  141  142   8   76  200  
3     189.0  137  141  11   72  211  
4     162.0  135  134   7   45  180  
...     ...  ...  ...  ..  ...  ...  
2991  183.0  142  144   9   78  213  
2992  123.0  143  149  11  115  155  
2993  123.0  143  149  11  115  155  
2994  199.0  142  138   6   65  231  
2995  123.0  143  149  11  115  155  

[2996 rows x 15 columns]

In [14]:
data["l"]

data = data.astype({"l":"int"})

data

name  season season2   vl  va  vb   vh   vs   vv    l   
0           winter (92).jpg  winter  winter  189   9  13   11   72  211  189  \
1           winter (94).jpg  winter  winter  179   9   6    5   44  197  179   
2           winter (84).jpg  winter  winter  176  13  14    8   76  200  176   
3           winter (92).jpg  winter  winter  171  23  56  114  170  131  189   
4           winter (80).jpg  winter  winter  162   7   6    7   45  180  162   
...                     ...     ...     ...  ...  ..  ..  ...  ...  ...  ...   
2991  autumn (7) (copy).jpg  autumn  autumn    2  23  57   18  176   21  183   
2992        autumn (14).PNG  autumn  autumn    2  18  10   18   70   37  123   
2993        autumn (14).PNG  autumn  autumn    1  15  32    3  116   23  123   
2994  autumn (1) (copy).jpg  autumn  autumn    1  10  13   11   13   13  199   
2995        autumn (14).PNG  autumn  autumn    1   1  30    7  108    4  123   

        a    b   h    s    v  
0     137  141  11   72  211  
1     137  134   5   44  197  
2     141  142   8   76  200  
3     137  141  11   72  211  
4     135  134   7   45  180  
...   ...  ...  ..  ...  ...  
2991  142  144   9   78  213  
2992  143  149  11  115  155  
2993  143  149  11  115  155  
2994  142  138   6   65  231  
2995  143  149  11  115  155  

[2996 rows x 15 columns]

In [15]:
import numpy as np

data_feature_names = ["l", "a", "b"]
data_target_names = np.array(["winter", "summer", "spring", "autumn"], dtype="U10")

data_target_names

array(['winter', 'summer', 'spring', 'autumn'], dtype='<U10')

In [16]:
data.columns

Index(['name', 'season', 'season2', 'vl', 'va', 'vb', 'vh', 'vs', 'vv', 'l',
       'a', 'b', 'h', 's', 'v'],
      dtype='object')

In [17]:
data_target_names = np.array(["winter", "summer", "spring", "autumn"], dtype="U10")

data_target_names

array(['winter', 'summer', 'spring', 'autumn'], dtype='<U10')

In [102]:
# input_data = data[["l", "a", "b"]]
# input_data

input_data = data[["vl", "va", "vb"]]
input_data

input_data = data[["vl", "va", "vb", "l", "a", "b","h","s","v"]]
input_data

vl  va  vb
0     189   9  13
1     179   9   6
2     176  13  14
3     171  23  56
4     162   7   6
...   ...  ..  ..
2991    2  23  57
2992    2  18  10
2993    1  15  32
2994    1  10  13
2995    1   1  30

[2996 rows x 3 columns]

In [103]:
input_target = data[["season"]]
input_target

season
0     winter
1     winter
2     winter
3     winter
4     winter
...      ...
2991  autumn
2992  autumn
2993  autumn
2994  autumn
2995  autumn

[2996 rows x 1 columns]

In [23]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [62]:
data_train = input_data.to_numpy()
data_train

array([[189, 137, 141],
       [179, 137, 134],
       [176, 141, 142],
       ...,
       [123, 143, 149],
       [199, 142, 138],
       [123, 143, 149]])

In [60]:
input_data

l    a    b
0     189  137  141
1     179  137  134
2     176  141  142
3     189  137  141
4     162  135  134
...   ...  ...  ...
2991  183  142  144
2992  123  143  149
2993  123  143  149
2994  199  142  138
2995  123  143  149

[2996 rows x 3 columns]

In [33]:
dt = data[["l", "a", "b", "season"]]
dt

l    a    b  season
0     189  137  141  winter
1     179  137  134  winter
2     176  141  142  winter
3     189  137  141  winter
4     162  135  134  winter
...   ...  ...  ...     ...
2991  183  142  144  autumn
2992  123  143  149  autumn
2993  123  143  149  autumn
2994  199  142  138  autumn
2995  123  143  149  autumn

[2996 rows x 4 columns]

In [35]:
season_dict = {
    "winter": 0, 
    "summer": 1,
    "spring": 2,
    "autumn": 3
}

In [39]:
season_dict["autumn"]

3

# train fit data만들기

In [104]:
data_train = input_data.to_numpy()
data_train

array([[189,   9,  13],
       [179,   9,   6],
       [176,  13,  14],
       ...,
       [  1,  15,  32],
       [  1,  10,  13],
       [  1,   1,  30]])

#  train fit y_target
## numpy array 만들어서 추가하기

In [105]:
data_target = np.array([], int)

for i in dt.index:    
    data_target = np.append(data_target, np.array([season_dict[dt.loc[i]["season"]]]))
    

data_target

array([0, 0, 0, ..., 3, 3, 3])

## list 만들어서 np.array 로 변환하기

In [57]:
d_list = []

for i in dt.index:    
    d_list.append(season_dict[dt.loc[i]["season"]])
    
    

print(d_list)
print(type(d_list))
print("")

d_list = np.array(d_list)

print(d_list)
print(type(d_list))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [106]:
# 데이터셋 분리 함수
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_train     #feature 
                                                    , data_target     #target
                                                    , stratify = data_target #층화추출법
                                                    , random_state = 13)  #난수고정

# 머신러닝 
## 디시전트리

In [101]:
from sklearn import tree


# 의사결정나무 분류 
clf = tree.DecisionTreeClassifier()               # 종속변수가 현재 범주형
clf = clf.fit(input_data, input_target)             # feature, target

In [100]:
# 시각화
dot_data = tree.export_graphviz(clf,   # 의사결정나무 모형 대입
                               out_file = None,  # file로 변환할 것인가
                               feature_names = data_feature_names,  # feature 이름
                               class_names = data_target_names,  # target 이름
                               filled = True,           # 그림에 색상을 넣을것인가
                               rounded = True,          # 반올림을 진행할 것인가
                               special_characters = True)   # 특수문자를 사용하나

graph = graphviz.Source(dot_data)              
graph

NameError: name 'graphviz' is not defined

In [107]:
from sklearn.metrics import confusion_matrix

clf.fit(X_train, y_train)

# test set predict confusion matrix
confusion_matrix(y_test,clf.predict(X_test))

array([[60, 35, 30, 62],
       [43, 68, 36, 40],
       [37, 34, 53, 37],
       [65, 54, 37, 58]])

# 검증

In [93]:
import cv2

img = cv2.imread("./color2/spring (11) (copy).jpg")

# hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

# h = hsv[:,:,0] # h 
# s = hsv[:,:,1] # s
# v = hsv[:,:,2] # v

lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)

l, a, b = cv2.split(lab)

l = int(np.median(l))
a = int(np.median(a))
b = int(np.median(b))

input_list = [[l, a, b]]
input_list

input_list = np.array(input_list)
input_list

array([[198, 137, 106]])

In [97]:
clf.predict(input_list)

array([0])

In [135]:
import cv2
import os

path = "./color/"
img_list = os.listdir(path)

r_count=0
f_count=0

color_df = pd.read_csv("./color_chart.txt")

season_list = ["winter","summer","spring","autumn"]

season_dict = {
    "winter": 0, 
    "summer": 1,
    "spring": 2,
    "autumn": 3
}

season_dict2 = {
    0: "winter", 
    1: "summer",
    2: "spring",
    3: "autumn"
}

cd = {"autumn" : "warm",
     "spring" : "warm",
     "summer": "cool",
     "winter": "cool"}

for i in img_list:
    img = cv2.imread(path+i)

    # hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

    # h = hsv[:,:,0] # h 
    # s = hsv[:,:,1] # s
    # v = hsv[:,:,2] # v

    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)

    l, a, b = cv2.split(lab)

    l = int(np.median(l))
    a = int(np.median(a))
    b = int(np.median(b))
    
    
    
    
            

    for k in season_list:
        
        data_target = np.empty((0,3), int)
        
        df_list = color_df[ color_df["season"] == k + "_" + cd[k]]

        for j in df_list.index:
            df_iloc = df_list.loc[j]
            vl = df_iloc["l"] - l
            va = df_iloc["a"] - a 
            vb = df_iloc["b"] - b
#             df_h = df_iloc["vh"]
#             df_s = df_iloc["vs"]
#             df_v = df_iloc["vv"]
            
            data_target = np.append(data_target, np.array([[vl, va, vb]]), axis=0)
        
#         print( np.bincount(clf.predict(data_target)) )
#         print( np.bincount(clf.predict(data_target)).argmax() )
#         print(season_dict2[np.bincount(clf.predict(data_target)).argmax()])
    if i.split(" ")[0] == season_dict2[np.bincount(clf.predict(data_target)).argmax()]:
        print(i.split(" ")[0], season_dict2[np.bincount(clf.predict(data_target)).argmax()])
        r_count+=1
    else:
        print(" --- ")
        f_count+=1
        
print("r :", r_count )
print("f :", f_count )      

#     if clf.predict(input_list)[0] == season_dict[i.split(" ")[0]]:
#         print(i.split(" ")[0], season_dict[i.split(" ")[0]], "pred :",clf.predict(input_list))
#         r_count+=1
#     else:
#         print(" --- ")
#         f_count+=1
        
# print("r :", r_count )
# print("f :", f_count )



 --- 
 --- 
winter winter
 --- 
winter winter
 --- 
winter winter
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
winter winter
winter winter
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
winter winter
winter winter
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
winter winter
 --- 
 --- 
winter winter
 --- 
 --- 
winter winter
 --- 
winter winter
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
winter winter
winter winter
 --- 
 --- 
 --- 
 --- 
winter winter
winter winter
winter winter
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
winter winter
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
winter winter
 --- 
 --- 
winter winter
 --- 
 --- 
spring spring
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
 --- 
winter winter
wi

In [130]:
data_target

array([[  83.,   35.,  -22.],
       [ -36.,   -1.,   -2.],
       [ -51.,   -5.,  -10.],
       [ 105.,  -39.,   13.],
       [  94.,  -51.,   13.],
       [  41.,    1.,  -10.],
       [ -77.,    1.,  -12.],
       [ -52.,    3.,   -8.],
       [ 118.,    0.,  -11.],
       [  64.,  -65.,    7.],
       [  79.,   -7.,   37.],
       [ 110.,  -21.,   33.],
       [ 124.,   22.,  -15.],
       [ -64.,   -5.,  -15.],
       [  74.,   24.,   -1.],
       [ 178.,    1.,  -12.],
       [ -25.,   25.,  -12.],
       [ -60.,   10.,  -22.],
       [ 115.,  -48.,   -4.],
       [ 105.,  -51.,  -31.],
       [ 160.,  -31.,   31.],
       [ 115.,  -26.,   -4.],
       [ -56.,   17.,  -82.],
       [ -56.,    1.,  -11.],
       [   5.,   32.,    9.],
       [  74.,    1.,  -11.],
       [  31.,   12.,   28.],
       [ -54.,   11.,   -9.],
       [ -66.,    5.,  -24.],
       [ -46.,    6.,  -32.],
       [ -33.,    5.,  -18.],
       [  73.,    1.,  -11.],
       [ -13.,    4.,   -8.],
       [  

In [129]:
import cv2
import os

path = "./color/"
img_list = os.listdir(path)

r_count=0
f_count=0

color_df = pd.read_csv("./color_chart.txt")

season_list = ["winter","summer","spring","autumn"]

season_dict = {
    "winter": 0, 
    "summer": 1,
    "spring": 2,
    "autumn": 3
}

season_dict2 = {
    0: "winter", 
    1: "summer",
    2: "spring",
    3: "autumn"
}

cd = {"autumn" : "warm",
     "spring" : "warm",
     "summer": "cool",
     "winter": "cool"}

print("    ", season_list)

for i in img_list:
    img = cv2.imread(path+i)

    # hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

    # h = hsv[:,:,0] # h 
    # s = hsv[:,:,1] # s
    # v = hsv[:,:,2] # v

    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)

    l, a, b = cv2.split(lab)

    l = int(np.median(l))
    a = int(np.median(a))
    b = int(np.median(b))
    
    
    
    
    data_target = np.empty((0,3), int)    

    for k in season_list:
        
        df_list = color_df[ color_df["season"] == k + "_" + cd[k]]

        for j in df_list.index:
            df_iloc = df_list.loc[j]
            vl = l - df_iloc["l"]
            va = a - df_iloc["a"]
            vb = b - df_iloc["b"]
#             df_h = df_iloc["vh"]
#             df_s = df_iloc["vs"]
#             df_v = df_iloc["vv"]
            
            data_target = np.append(data_target, np.array([[vl, va, vb]]), axis=0)
        
    print( i.split(" ")[0], np.bincount(clf.predict(data_target)) )
#     print( np.bincount(clf.predict(data_target)).argmax() )
#     print(season_dict2[np.bincount(clf.predict(data_target)).argmax()])
    
#     if clf.predict(input_list)[0] == season_dict[i.split(" ")[0]]:
#         print(i.split(" ")[0], season_dict[i.split(" ")[0]], "pred :",clf.predict(input_list))
#         r_count+=1
#     else:
#         print(" --- ")
#         f_count+=1
        
# print("r :", r_count )
# print("f :", f_count )



     ['winter', 'summer', 'spring', 'autumn']
summer [ 7  7 77 16]
summer [ 4 12 64 27]
winter [13 10 66 18]
autumn [10 12 72 13]
winter [11  9 62 25]
autumn [13  6 67 21]
winter [ 4  9 76 18]
spring [16  9 57 25]
summer [ 8 12 54 33]
winter [ 7 12 69 19]
spring [13 16 48 30]
winter [ 3  7 82 15]
spring [12 18 51 26]
winter [13 10 57 27]
winter [ 8 12 64 23]
autumn [ 7  8 72 20]
winter [12  5 70 20]
spring [10 11 65 21]
spring [15 13 49 30]
summer [11  8 63 25]
summer [13 12 49 33]
autumn [11  8 66 22]
winter [16 15 43 33]
spring [17  9 52 29]
autumn [11  9 59 28]
summer [11 15 58 23]
summer [14  8 64 21]
winter [ 5 10 76 16]
winter [11  9 58 29]
summer [14 16 48 29]
summer [12 11 65 19]
summer [ 9 14 60 24]
summer [15 11 52 29]
winter [14  9 56 28]
summer [ 9  5 65 28]
summer [10  8 72 17]
autumn [ 4 11 69 23]
summer [18 10 52 27]
spring [16 13 54 24]
winter [11 14 71 11]
spring [13 11 63 20]
winter [ 8 11 73 15]
autumn [16  9 60 22]
summer [ 9 10 73 15]
winter [ 9 16 52 30]
spring [ 

autumn [ 9  7 71 20]
autumn [11 18 53 25]
summer [12  9 57 29]
spring [ 5 17 55 30]
spring [11 12 60 24]
summer [ 6 18 57 26]
winter [18 13 49 27]
winter [ 6 11 76 14]
summer [11 12 55 29]
spring [14 11 57 25]
summer [ 7 17 53 30]
winter [ 9  5 68 25]
summer [16 15 47 29]
summer [12  9 61 25]
spring [17 10 60 20]
summer [ 9 15 54 29]
spring [12 11 60 24]
winter [ 7 16 57 27]
autumn [13  8 64 22]
summer [15  8 58 26]
winter [ 5 12 66 24]
summer [16 12 54 25]
winter [13 17 49 28]
summer [17 12 49 29]
winter [11 15 56 25]
summer [10 10 61 26]
winter [12 11 55 29]
spring [16 11 53 27]
autumn [10  8 67 22]
autumn [ 9 12 56 30]
summer [13 13 49 32]
spring [11 16 43 37]
summer [ 8  7 70 22]
spring [ 8 10 59 30]
spring [12 15 56 24]
summer [13 13 53 28]
spring [14 14 51 28]
spring [ 9 12 62 24]
winter [11 12 62 22]
summer [10 13 54 30]
autumn [ 8  5 64 30]
spring [11 10 57 29]
winter [ 9  8 65 25]
spring [12  8 63 24]
winter [ 9 12 72 14]
winter [ 9 13 70 15]
summer [10  7 66 24]
winter [11 13

In [75]:
import cv2
import numpy as np

import pandas as pd

cd = {"autumn" : "warm",
     "spring" : "warm",
     "summer": "cool",
     "winter": "cool"}

season_list = ["spring", "summer", "autumn", "winter"]

for i in range(1, 100):
    img = cv2.imread(f"./color/spring ({i}).jpg")
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)

    h = hsv[:,:,0] # h 
    s = hsv[:,:,1] # s
    v = hsv[:,:,2] # v

    h = int(np.median(h))
    s = int(np.median(s))
    v = int(np.median(v))

    l, a, b = cv2.split(lab)

    l = int(np.median(l))
    a = int(np.median(a))
    b = int(np.median(b))


    l,a,b,h,s,v

    color_df = pd.read_csv("./color_chart.txt")


    for k in season_list:

        df_list = color_df[ color_df["season"] == k + "_" + cd[k]]

        for j in df_list.index:
            df_iloc = df_list.loc[j]
            df_l = df_iloc["l"]
            df_a = df_iloc["a"]
            df_b = df_iloc["b"]
    #         df_h = df_iloc["h"]
    #         df_s = df_iloc["s"]
    #         df_v = df_iloc["v"]

            if ((df_l - l) > 130 and (df_l - l) < 140):
                if ((df_a - a) == 0 or (df_b - b)<=20):
                    print("spring")
                    print(i)
                    print(l,a,b)
            elif (df_l - l) <= 10:
                if (df_a - a) == 0:
                    if (df_b - b) <=20:
                        print("spring")
                        print(i)
                        print(l,a,b)
            else:
                pass

spring
2
172 134 144
spring
3
184 134 138
spring
7
185 134 136
spring
14
179 139 139
spring
14
179 139 139
spring
16
157 136 140
spring
16
157 136 140
spring
18
205 139 132
spring
18
205 139 132
spring
20
182 139 144
spring
20
182 139 144
spring
26
131 139 133
spring
29
169 139 140
spring
29
169 139 140
spring
32
185 134 138
spring
33
191 134 137
spring
36
187 134 138
spring
40
197 132 136
spring
41
208 132 134
spring
42
200 135 144
spring
43
181 136 138
spring
43
181 136 138
spring
46
170 139 131
spring
46
170 139 131
spring
54
193 136 139
spring
54
193 136 139
spring
56
168 139 137
spring
56
168 139 137
spring
58
207 136 141
spring
58
207 136 141
spring
58
207 136 141
spring
60
195 136 141
spring
60
195 136 141
spring
62
177 134 133
spring
64
208 134 136
spring
64
208 134 136
spring
67
196 136 139
spring
67
196 136 139
spring
68
193 136 136
spring
68
193 136 136
spring
80
202 135 144
spring
82
117 133 142
spring
83
169 139 138
spring
83
169 139 138
spring
84
178 139 136
spring
84
178